### ISSUE TITLE
Wrong msg to stderr?

### ISSUE THREAD

**Issue by grammoboy2** [rncbc/padthv1#11]
NSM: Successfully registered with server

This message is send to stderr, should go to stdout.

**Comment by rncbc** [comment]
is that a big concern? ;)

if it fails it might also send "NSM: Failed to register with server"  to stdout (2) not stderr (3)...

**Comment by grammoboy2** [comment]
It's a big concern because it's quite a essential convention on Unix, if you want multiple processes to work together smoothly afaik. So it probably should be a no brainer when developing for Linux/Unix, errors goes to stderr (that's 2 right?), other messages to stdout(1), even if you don't see the value in it for a specific project yet.

For my specific use-case, I think it should be possible to split stdout/stderr streams from nsmd.

**Comment by rncbc** [comment]
maybe the question is better posed as this: does it ever interfere or ever block or perclude any of the NSM functionality ?

i see this as just an insignificant nitpick, but well, you may have other reasons :)

cheers

**Comment by grammoboy2** [comment]
Don't blame the nitpicking on me. There is a essential convention on Unix since 1969, but mister procrastinator wants his own convention, randomly selecting the file descriptor 1 or 2 (it's probably copied from NON software though). ;)

If you split stdout and stderr it's possible to make a choice, it controllable. Now it can't be controlled. Suppose every NSM client would strictly handle stdout and stderr, there is a choice. 

Now it's just a enormous flood of messages, nsmd logging messages combined with all the logging message of the clients (stderr and stdout). It would be much cleaner and nicer to work with, if only the error messages of the NSM clients would join the logging messages of nsmd. And even if you disagree, it's not good if there is no choice. For lots of things this redirection convention is quite essential I can imagine. 

From what I read, on Unix one rule is: silence is golden, which means, don't report when everything is fine and if it fails, fail loud. So error messages are important I think, you can't skip them to be less verbose. 

Another kind of convention seems to be to stick with the original terminal width, 80 I believe. So keep messages short.

Logging is a matter of taste I think. In the case of nsmd, you want to see a nice flow of events happening, while keeping it readable, less is more probably though. Not saying that I'm a logging expert...

**Comment by rncbc** [comment]
fixed in develop branch 433b311

cheers
