### ISSUE TITLE
No need to manually strip binaries with cmake

### ISSUE THREAD

**Issue by yurivict** [rncbc/padthv1#4]
Hi,

This section in this project and your other projects:
https://github.com/rncbc/padthv1/blob/master/src/CMakeLists.txt#L175
is most likely wrong, because cmake strips built binaries in the ```install``` target automatically. No need to run custom commands for this during build, and build is a wrong time for this.

You need to add comments explaining why custom actions like this are needed.

Thanks,
Yuri

**Comment by rncbc** [comment]
whatever, cmake stuff is not there anyway, and probably it won't for quite some time on the vee-one front :)

cheers

**Comment by yurivict** [comment]
> whatever, cmake stuff is not there anyway

I use cmake with a Qt-based project and it is very reliable for me.

-----------------

The build breaks on FreeBSD:
```
strip -v padthv1_jack
strip: invalid option -- v
Usage: strip [options] file...
  Discard information from ELF objects.
```

**Comment by yurivict** [comment]
So the synopsys is:
1. cmake doesn't need the ```strip``` command, and it is broken on BSDs as it is there
2. The qmake file has a broken ```strip``` command: ```-v``` isn't supported on BSDs
3. The cmake build is broken with a ```missing include``` problem, see the other bug report.

**Comment by rncbc** [comment]
if you wish you can fix the cmake build scripts, please do a PR 

1. you may well get rid of the `strip` command on cmake build;
2. drop the `-v` on the official qmake, it does not hurt the less;
3. add the missing include if you know what it is;

thanks

**Comment by yurivict** [comment]
I'm only a port maintainer, and don't have resources for PRs, sorry!

**Comment by rncbc** [comment]
maybe fixed in the [[xstrip](https://github.com/rncbc/padthv1/tree/xstrip)] branch, commit https://github.com/rncbc/padthv1/commit/15d14969 ... please test and tell...

cheers

**Comment by yurivict** [comment]
This commit has this problem fixed.

Thanks!
