### ISSUE TITLE
cmake build fails: fatal error: 'ui_padthv1widget_palette.h' file not found

### ISSUE THREAD

**Issue by yurivict** [rncbc/padthv1#5]
```
#include "ui_padthv1widget_palette.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by rncbc** [comment]
i get that in `src/CMakeLists.txt` is missing one line `padthv1widget_config.ui` on the `set (FORMS_UI ... )`

same with the other vee-ones...

**Comment by rncbc** [comment]
maybe fixed in the [[xstrip](https://github.com/rncbc/padthv1/tree/xstrip)] branch, commit https://github.com/rncbc/padthv1/commit/15d14969 ... please test and tell...

cheers

**Comment by yurivict** [comment]
This commit has this problem fixed.

Thanks!
