### ISSUE TITLE
[regression in 0.9.18] checking for Qt install libraries... 

### ISSUE THREAD

**Issue by yurivict** [rncbc/padthv1#6]
All these ports audio/synthv1-lv2 audio/samplv1-lv2 audio/padthv1-lv2 audio/drumkv1-lv2 fail with the following error for the version ```0.9.18```:

```
checking for qtchooser... /usr/local/bin/qtchooser
checking for qmake... /usr/local/bin/qmake
checking for Qt major version... qmake: could not find a Qt installation of '5'
0
checking for Qt install path... qmake: could not find a Qt installation of '5'

checking for qmake... /usr/local/bin/qmake
checking for Qt install headers... qmake: could not find a Qt installation of '5'

checking for Qt install libraries... qmake: could not find a Qt installation of '5'

checking for Qt library version >= 5.1... no; Qt 5.1 or greater is required
===>  Script "configure" failed unexpectedly.
```

FreeBSD 12.2
Qt-5.15 is installed.

**Comment by rncbc** [comment]
never seen Qt installed on /usr/local ...

though in that case what exactly is the output of:
`/usr/local/bin/qmake -version`
and
`/usr/local/bin/qmake -query QT_VERSION`

this message is quite frankly suspicious:
`qmake: could not find a Qt installation of '5'`

**Comment by yurivict** [comment]
```
$ /usr/local/bin/qmake -version
QMake version 3.1
Using Qt version 5.15.0 in /usr/local/lib/qt5
$ /usr/local/bin/qmake -query QT_VERSION
5.15.0
```

**Comment by rncbc** [comment]
please try again in this order:
```
./autogen.sh clean
./autogen.sh
./configure 
```
look after `config.log` for reasons it's gone in error.

one other suspicion goes to the existence of `qtchooser`... does it really make any sense having it still installed in your system?

**Comment by yurivict** [comment]
```
configure:4656: checking for Qt library version >= 5.1
configure:4677: c++ -c -std=c++17 -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer   -I -fPIC -fno-omit-frame-pointer conftest.cpp >&5
conftest.cpp:16:10: fatal error: 'QtCore/qglobal.h' file not found
#include "QtCore/qglobal.h"
         ^~~~~~~~~~~~~~~~~~
1 error generated.
```

You need to add ```pkg-config --cflang --libs QtCore``` ?

**Comment by rncbc** [comment]
that's the last straw... previous config/qmake checks failed to set proper CFLAGS for that to work at all.

**Comment by yurivict** [comment]
All your *v1 projects have the same problem.

**Comment by yurivict** [comment]
cmake works, thanks!
